Уважаемые студенты!

Задачи выполняются с помощью стандартных библиотек питона без установки сторонних библиотек. Все задачи направлены на проверку усвоения пройденного материала. Вспомните как работать с библиотекой numpy.

Желаем удачи!

**Задача №1**. **Написать формулу которая находит ближайшее значение к переменной x из значений в массиве X:**

- Подсказка 1: np.abs, argmin, flat
- Подсказка 2: Для значений:
> X = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])
>
> x = 0.5
> Правильный ответ будет: 0.48059102


In [ ]:
# место для решения - DONE

# Решу поэтапно

import numpy as np

def nearest_value(X_arr, x_var):
  dist = np.abs(X_arr - x_var)
  min_dist = dist.argmin()
  nearest_value_1  = X_arr[min_dist]
  result = print(nearest_value_1)
  return result

# проверим
X = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])

nearest_value(X, 0.5)

0.48059102


**Задача №2**. **Какой из следующих массивов является двумерным (2D) массивом?**

1. 56
2. [[4,6,7], [8,6,8]]
3. [4, 6, 7]



In [ ]:
# место для ответа - DONE

a1 = np.array([[4,6,7], [8,6,8]])

a1.shape

# => [[4,6,7], [8,6,8]] является двумерным (2D) массивом?


(2, 3)

**Задача №3**. **Как правильно сделать print числа 7 из массива:**

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

    1. print(arr[7,2])
    2. print(arr[2,0])
    3. print(arr[1,1])


In [ ]:
# место для ответа  - DONE

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, 1])

7


**Задача №4**. **Как правильно сделать массив [3, 4, 5, 6] из массива:**

arr = np.array([1,2,3,4,5,6,7,8,9])

    1. print(arr[2:6])
    2. print(arr[2:5])
    3. print(arr[3:6])
    4. print(arr[1:6])

In [ ]:
# место для ответа - DONE

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2:6])

[3 4 5 6]


**Задача №5**. **Какое выражение выведет каждый второй элемент из массива:**

arr = np.array([1,2,3,4,5,6,7])

    1. print(arr[1:3:5:7])
    2. print(arr[::2])
    3. print(arr(0: step=2))

In [ ]:
# место для ответа - DONE

arr = np.array([1,2,3,4,5,6,7])

print(arr[::2])

# 2. print(arr[::2])


[1 3 5 7]


**Задача №6**. **Как правильно сделать массив индексов всех элементов, имеющих значение 4 из массива ниже:**

arr = np.array([1,4,3,4,5,4,4])

    1. arr.where(4)
    2. np.where(arr==4)
    3. arr.search(4)

In [ ]:
# место для ответа - DONE

arr = np.array([1,4,3,4,5,4,4])
np.where(arr == 4)

(array([1, 3, 5, 6]),)

**Задача №7**. **Написать формулу которая создает матрицу (двумерный массив) 3x3 со значениями от 0 до 8**

In [ ]:
# место для решения - DONE

# до 8 - эквивалентно включая 8 или не включая 8?

matrix = np.arange(0, 9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**Задача №8**. **Используя формулы numpy создать матрицу m с 1 внутри и 0 на границах**

Подсказка 1: np.zeros

Подсказка 2: матрица будет такая:

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# место для решения - DONE


matrix = np.array([[0., 0., 0., 0., 0.], [0., 1., 1., 1., 0.], [0., 1., 1., 1., 0.], [0., 1., 1., 1., 0.], [0., 0., 0., 0., 0.]])


m = np.zeros((5, 5))
m[1:4, 1:4] = 1
print(m)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**Задача №9**. **Создайте вектор размером 10 со значениями в диапазоне от 0 до 1, 0 и 1 не должны быт в этом векторе.**

Подсказка: np.linspace

In [ ]:
# место для решения - DONE


vec = np.linspace(0, 1, 10)
vec = vec[(vec > 0) & (vec < 1)]
print(vec)

[0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667
 0.77777778 0.88888889]


**Задача №10**. **Что выведет код:**

a = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)

1. 1
2. (1,3)
3. 3
4. (3,1)

In [ ]:
# место для ответа - DONE

# Код выведет число измерений в массиве.

a = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)

3


**Задача №11**. **Что из перечисленного является правильным способом транспонирования матрицы A?**

    1. Trans(A)
    2. Transpose(A)
    3. A.T
    4. A.Transpose


In [ ]:
# место для ответа - DONE

A = np.array([[1, 2], [3, 4]])
A.T # ВЕРНЫЙ МЕТОД

# A.transpose() - если с маленькой буквы, то тоже верно.

array([[1, 3],
       [2, 4]])

**Задача №12**. **Что выведет print в коде:**

a = np.array([1,2,3,4,5])

b = np.arange(0,10,2)

c = a + b

print (c[4])


In [ ]:
# место для ответа - DONE

a = np.array([1,2,3,4,5]) # создаем массив a

b = np.arange(0,10,2) # создаем массив b, заполненный значениями из диапазона
                      # от 0 до 10 с шагом 2
c = a + b # суммируем два массива поэлементно

print (c[4]) # так как получившийся массив - одномерный, просто вытаскиваем
             # оттуда один элемет под индексом 4

# 13 - элемент итогового массива под индексом 4.

13
